### PR TITLE
removed and replaced deprecated React.PropTypes with 'prop-types' package

### LINKED ISSUE #98: Accessing PropTypes via the main React package is deprecated.
is there any alternative way to bypass the react version? I think this package should compatible for currently react version.

### PR DESCRIPTION
**Pull request by donovanhiland**
fixes #98

### CODE REVIEW

**Comment by pipa** [comment]
when will this be merged?

**Comment by davidsonfellipe** [comment]
@pipa Last merge 2.5 months ago. 😟

**Comment by donovanhiland** [comment]
Im using [react-validation-temp](https://www.npmjs.com/package/react-validation-temp) until this is merged into the main repo and released. All the same but with these changes

**Comment by yamat124** [comment]
Some please merge this.

**Pull request merged**
