### PR TITLE
onChange event passes value along with event

### PR DESCRIPTION
**Pull request by kaela**
This change allows the onChange handler to receive that value as well as the event.

### CODE REVIEW

**Comment by Lesha-spr** [comment]
Hi Kaela,

Thank you for PR.

I've a question about it. Why you would want to receive value itself as an argument to handler? If you're performing 'native' event - value would be passed as an `event.target.value`. If you're changing value via `setValue` - then you obviously have this value :)

Maybe there is some case I'm not aware of? So please provide your use-case.

Thank you in advance.

**Comment by dbachrach** [comment]
@Lesha-spr We have tracked this down to its root cause, and I've opened a [new pr](https://github.com/Lesha-spr/react-validation/pull/12) instead.

**Comment by Lesha-spr** [comment]
Hi guys,

Should I close this pr?

Thanks,
Oleksii

**Comment by dbachrach** [comment]
Yeah, this should be closed. Thanks.

**Pull request closed without merging**
